name: EAS Update (Preview)
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.json'
      - '**.lock'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    environment:
      name: ENV
    env:
      VARS_CONTEXT: ${{ toJson(vars) }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Set environment variables
        run: |
          echo "$VARS_CONTEXT" | 
          jq -r 'to_entries | 
          .[] | 
          "\(.key)=\(.value)"' >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish update
        run: eas update --channel preview --auto --clear-cache --non-interactive
